# Licensed under the Apache-2.0 license

[toolchain]
channel = "nightly-2025-07-20"
components = ["clippy", "rust-src", "llvm-tools", "rustfmt", "rustc-dev"]
targets = [
  "x86_64-unknown-linux-gnu",
]
profile = "default"
