# Licensed under the Apache-2.0 license

[package]
name = "xtask"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
xshell = "0.2"
walkdir = "2.0"
