// Licensed under the Apache-2.0 license
// SPDX-License-Identifier: Apache-2.0

use clap::Parser;
use quote::quote;
use std::collections::HashSet;
use std::fs;
use std::path::PathBuf;
use syn::{parse_quote, Attribute, Fields, File, Ident, Item, ItemStruct, Type};

#[derive(Parser, Debug)]
#[command(
    author,
    version,
    about = "Transform Rust FFI bindings for OpenTitan libotcrypto using Rust AST (syn)"
)]
struct Args {
    /// Path to raw input Rust bindings file (generated by bindgen)
    #[arg(short, long)]
    input: PathBuf,

    /// Output path for generated idiomatic Rust bindings
    #[arg(
        short,
        long,
        default_value = "target/earlgrey/cryptolib/src/otcrypto_sys.rs"
    )]
    out: PathBuf,
}

pub fn to_pascal_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = true;
    for c in s.chars() {
        if c == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(c);
        }
    }
    result
}

pub fn sanitize_variant(name: &str) -> String {
    if let Some(first) = name.chars().next() {
        if first.is_ascii_digit() {
            format!("V{name}")
        } else {
            name.to_string()
        }
    } else {
        name.to_string()
    }
}

pub fn rename_type(name: &str) -> Option<String> {
    const PRIMITIVES: &[&str] = &[
        "u8", "u16", "u32", "u64", "usize", "i8", "i16", "i32", "i64", "isize", "bool", "c_void",
    ];
    if PRIMITIVES.contains(&name) {
        return None;
    }
    let clean = name.strip_suffix("_t").unwrap_or(name);
    let stripped = clean.strip_prefix("otcrypto_").unwrap_or(clean);
    let pascal = to_pascal_case(stripped);
    if pascal == name {
        None
    } else {
        Some(pascal)
    }
}

pub fn map_enum_variant_name(enum_name: &str, variant_name: &str) -> String {
    match variant_name {
        name if name.starts_with("kHardenedBool") => {
            let stripped = name.strip_prefix("kHardenedBool").unwrap_or(name);
            to_pascal_case(stripped)
        }
        name if name.starts_with("kOtcrypto") => {
            let mut stripped = name.strip_prefix("kOtcrypto").unwrap_or(name);
            let clean = enum_name.strip_prefix("enum ").unwrap_or(enum_name);
            let clean = clean.strip_prefix("otcrypto_").unwrap_or(clean);
            let clean = clean.strip_suffix("_t").unwrap_or(clean);

            let pascal_ename = to_pascal_case(clean);
            if let Some(tail) = stripped.strip_prefix(&pascal_ename)
                && !tail.is_empty()
            {
                stripped = tail;
            } else if let Some(tail) = stripped.strip_prefix("HashXofMode")
                && !tail.is_empty()
            {
                stripped = tail;
            }

            let pascal = to_pascal_case(stripped);
            sanitize_variant(&pascal)
        }
        _ => sanitize_variant(&to_pascal_case(variant_name)),
    }
}

pub fn rename_fn(name: &str) -> Option<String> {
    name.strip_prefix("otcrypto_").map(ToString::to_string)
}

/// Check whether a type contains raw pointers.
fn has_raw_pointer(ty: &Type) -> bool {
    match ty {
        Type::Ptr(_) => true,
        Type::Array(a) => has_raw_pointer(&a.elem),
        Type::Slice(s) => has_raw_pointer(&s.elem),
        Type::Reference(r) => has_raw_pointer(&r.elem),
        Type::Tuple(t) => t.elems.iter().any(has_raw_pointer),
        _ => false,
    }
}

/// Automatically determines if a struct is a Plain-Old-Data (POD) struct
/// that can safely derive zerocopy traits (has no pointer fields).
pub fn is_pod_struct(s: &ItemStruct) -> bool {
    match &s.fields {
        Fields::Named(fields) => !fields.named.iter().any(|f| has_raw_pointer(&f.ty)),
        Fields::Unnamed(fields) => !fields.unnamed.iter().any(|f| has_raw_pointer(&f.ty)),
        Fields::Unit => true,
    }
}

fn add_zerocopy_derives(attrs: &mut Vec<Attribute>) {
    for attr in attrs.iter_mut() {
        if attr.path().is_ident("derive")
            && let syn::Meta::List(ref mut list) = attr.meta
        {
            let tokens_str = list.tokens.to_string();
            if !tokens_str.contains("IntoBytes") {
                let old_tokens = &list.tokens;
                list.tokens = parse_quote!(#old_tokens, IntoBytes, Immutable, KnownLayout);
            }
            return;
        }
    }
    attrs.push(parse_quote!(#[derive(IntoBytes, Immutable, KnownLayout)]));
}

fn rename_type_in_type(ty: &mut Type) {
    match ty {
        Type::Path(tp) => {
            if let Some(last) = tp.path.segments.last_mut() {
                let name = last.ident.to_string();
                if let Some(new_name) = rename_type(&name) {
                    last.ident = Ident::new(&new_name, last.ident.span());
                }
            }
        }
        Type::Ptr(p) => {
            rename_type_in_type(&mut p.elem);
        }
        Type::Reference(r) => {
            rename_type_in_type(&mut r.elem);
        }
        Type::Array(a) => {
            rename_type_in_type(&mut a.elem);
        }
        Type::Slice(s) => {
            rename_type_in_type(&mut s.elem);
        }
        _ => {}
    }
}

pub fn transform_ast(source: &str) -> Result<String, Box<dyn std::error::Error>> {
    let mut file: File = syn::parse_file(source)?;

    // 1. Process structs, enums, functions, and types
    for item in &mut file.items {
        match item {
            Item::Struct(s) => {
                let orig_name = s.ident.to_string();
                if let Some(new_name) = rename_type(&orig_name) {
                    s.ident = Ident::new(&new_name, s.ident.span());
                }
                let current_name = s.ident.to_string();

                if let Fields::Named(ref mut fields) = s.fields {
                    for field in &mut fields.named {
                        let fname = field
                            .ident
                            .as_ref()
                            .map(|i| i.to_string())
                            .unwrap_or_default();
                        if current_name.ends_with("Key") && (fname == "keyblob" || fname == "key") {
                            field.ty = parse_quote!(u32);
                        } else {
                            rename_type_in_type(&mut field.ty);
                        }
                    }
                }

                if is_pod_struct(s) {
                    add_zerocopy_derives(&mut s.attrs);
                }
            }
            Item::Enum(e) => {
                let orig_name = e.ident.to_string();
                if let Some(new_name) = rename_type(&orig_name) {
                    e.ident = Ident::new(&new_name, e.ident.span());
                }

                for variant in &mut e.variants {
                    let vname = variant.ident.to_string();
                    let clean_vname = map_enum_variant_name(&orig_name, &vname);
                    variant.ident = Ident::new(&clean_vname, variant.ident.span());
                }

                add_zerocopy_derives(&mut e.attrs);
            }
            Item::ForeignMod(fm) => {
                for foreign_item in &mut fm.items {
                    if let syn::ForeignItem::Fn(f) = foreign_item {
                        let orig_name = f.sig.ident.to_string();
                        if let Some(new_name) = rename_fn(&orig_name) {
                            f.sig.ident = Ident::new(&new_name, f.sig.ident.span());
                        }
                        for arg in &mut f.sig.inputs {
                            if let syn::FnArg::Typed(pat_type) = arg {
                                rename_type_in_type(&mut pat_type.ty);
                            }
                        }
                        if let syn::ReturnType::Type(_, ref mut ret_ty) = f.sig.output {
                            rename_type_in_type(ret_ty);
                        }
                    }
                }
            }
            Item::Type(t) => {
                let orig_name = t.ident.to_string();
                if let Some(new_name) = rename_type(&orig_name) {
                    t.ident = Ident::new(&new_name, t.ident.span());
                }
                rename_type_in_type(&mut t.ty);
            }
            _ => {}
        }
    }

    // 2. Filter out redundant type aliases and use items
    let defined_structs_and_enums: HashSet<String> = file
        .items
        .iter()
        .filter_map(|item| match item {
            Item::Struct(s) => Some(s.ident.to_string()),
            Item::Enum(e) => Some(e.ident.to_string()),
            _ => None,
        })
        .collect();

    file.items.retain(|item| match item {
        Item::Use(_) => false,
        Item::Const(c) => c.ident != "_",
        Item::Type(t) => {
            let alias_name = t.ident.to_string();
            let target_name = match &*t.ty {
                Type::Path(tp) => tp
                    .path
                    .segments
                    .last()
                    .map(|s| s.ident.to_string())
                    .unwrap_or_default(),
                _ => String::new(),
            };
            alias_name != target_name && !defined_structs_and_enums.contains(&alias_name)
        }
        _ => true,
    });

    // 3. Inject zerocopy imports and header comments
    let mut output = String::from(
        "// Generated by otcrypto_bindgen (AST pipeline). DO NOT EDIT.\n\
        #![allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code)]\n\n\
        use zerocopy::{Immutable, IntoBytes, KnownLayout};\n\n",
    );

    let code_tokens = quote!(#file);
    output.push_str(&code_tokens.to_string());

    // 4. Append accessor helper methods and hardware driver bindings
    let helpers = r#"

impl BlindedKey {
    /// Sets the pointer integer value to the keyblob buffer.
    #[inline]
    pub fn set_keyblob(&mut self, ptr: *mut u32) {
        self.keyblob = ptr as u32;
    }

    /// Returns the raw pointer to the keyblob buffer.
    #[inline]
    pub fn keyblob_ptr(&self) -> *mut u32 {
        self.keyblob as *mut u32
    }
}

impl UnblindedKey {
    /// Sets the pointer integer value to the key buffer.
    #[inline]
    pub fn set_key(&mut self, ptr: *mut u32) {
        self.key = ptr as u32;
    }

    /// Returns the raw pointer to the key buffer.
    #[inline]
    pub fn key_ptr(&self) -> *mut u32 {
        self.key as *mut u32
    }
}

unsafe extern "C" {
    /// Direct hardware-accelerated SHA-256 computation via Earlgrey HMAC HWIP.
    pub fn hmac_hash_sha256(msg: *const ConstByteBuf, digest: *mut u32) -> Status;

    /// Direct hardware-accelerated SHA-384 computation via Earlgrey HMAC HWIP.
    pub fn hmac_hash_sha384(msg: *const ConstByteBuf, digest: *mut u32) -> Status;

    /// Direct hardware-accelerated SHA-512 computation via Earlgrey HMAC HWIP.
    pub fn hmac_hash_sha512(msg: *const ConstByteBuf, digest: *mut u32) -> Status;
}
"#;
    output.push_str(helpers);

    Ok(output)
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args = Args::parse();

    let raw_rust = fs::read_to_string(&args.input)
        .map_err(|e| format!("Failed to read raw input file {:?}: {e}", args.input))?;

    let transformed = transform_ast(&raw_rust)?;

    if let Some(parent) = args.out.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&args.out, transformed)?;
    println!(
        "Successfully wrote idiomatic Rust FFI bindings to {:?}",
        args.out
    );

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_to_pascal_case() {
        assert_eq!(to_pascal_case("key_config"), "KeyConfig");
        assert_eq!(to_pascal_case("blinded_key"), "BlindedKey");
        assert_eq!(to_pascal_case("status_value"), "StatusValue");
    }

    #[test]
    fn test_sanitize_variant() {
        assert_eq!(sanitize_variant("Aes"), "Aes");
        assert_eq!(sanitize_variant("128"), "V128");
        assert_eq!(sanitize_variant("Sha256"), "Sha256");
    }

    #[test]
    fn test_rename_type() {
        assert_eq!(rename_type("otcrypto_status_t"), Some("Status".to_string()));
        assert_eq!(rename_type("status_t"), Some("Status".to_string()));
        assert_eq!(
            rename_type("hardened_bool_t"),
            Some("HardenedBool".to_string())
        );
        assert_eq!(
            rename_type("otcrypto_status_value_t"),
            Some("StatusValue".to_string())
        );
        assert_eq!(
            rename_type("otcrypto_blinded_key_t"),
            Some("BlindedKey".to_string())
        );
        assert_eq!(
            rename_type("otcrypto_key_config_t"),
            Some("KeyConfig".to_string())
        );
    }

    #[test]
    fn test_rename_fn() {
        assert_eq!(rename_fn("otcrypto_sha2_256"), Some("sha2_256".to_string()));
        assert_eq!(
            rename_fn("otcrypto_aes_gcm_encrypt"),
            Some("aes_gcm_encrypt".to_string())
        );
    }

    #[test]
    fn test_enum_variant_mappings() {
        assert_eq!(
            map_enum_variant_name("hardened_bool_t", "kHardenedBoolTrue"),
            "True".to_string()
        );
        assert_eq!(
            map_enum_variant_name("otcrypto_status_value_t", "kOtcryptoStatusValueOk"),
            "Ok".to_string()
        );
        assert_eq!(
            map_enum_variant_name("otcrypto_key_type_t", "kOtcryptoKeyTypeAes"),
            "Aes".to_string()
        );
        assert_eq!(
            map_enum_variant_name("otcrypto_rsa_size_t", "kOtcryptoRsaSize2048"),
            "V2048".to_string()
        );
        assert_eq!(
            map_enum_variant_name("otcrypto_hash_mode_t", "kOtcryptoHashModeSha3_256"),
            "Sha3256".to_string()
        );
        assert_eq!(
            map_enum_variant_name("otcrypto_hash_mode_t", "kOtcryptoHashXofModeShake128"),
            "Shake128".to_string()
        );
    }

    #[test]
    fn test_transform_ast_end_to_end() {
        let raw_snippet = r#"
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct otcrypto_blinded_key {
    pub config: otcrypto_key_config_t,
    pub keyblob_length: usize,
    pub keyblob: *mut u32,
    pub checksum: u32,
}
pub type otcrypto_blinded_key_t = otcrypto_blinded_key;

#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum otcrypto_key_type {
    kOtcryptoKeyTypeAes = 0,
    kOtcryptoKeyTypeHmac = 1,
}
pub type otcrypto_key_type_t = otcrypto_key_type;

unsafe extern "C" {
    pub fn otcrypto_sha2_256(
        message: otcrypto_const_byte_buf_t,
        digest: *mut otcrypto_hash_digest_t,
    ) -> status_t;
}
"#;
        let result = transform_ast(raw_snippet).expect("AST transform failed");
        assert!(result.contains("struct BlindedKey"));
        assert!(result.contains("keyblob : u32") || result.contains("keyblob: u32"));
        assert!(result.contains("enum KeyType"));
        assert!(result.contains("Aes = 0"));
        assert!(result.contains("Hmac = 1"));
        assert!(result.contains("fn sha2_256"));
        assert!(result.contains("IntoBytes"));
        assert!(result.contains("Immutable"));
        assert!(result.contains("KnownLayout"));
    }

    #[test]
    fn test_is_pod_struct() {
        let pod: ItemStruct = parse_quote! {
            pub struct Foo {
                pub a: u32,
                pub b: usize,
                pub c: [u32; 16],
            }
        };
        assert!(is_pod_struct(&pod));

        let with_ptr: ItemStruct = parse_quote! {
            pub struct Bar {
                pub data: *mut u8,
                pub len: usize,
            }
        };
        assert!(!is_pod_struct(&with_ptr));
    }
}
