# Licensed under the Apache-2.0 license
# SPDX-License-Identifier: Apache-2.0

baudrate = 115200

[device_a]  # master
srst_pin    = 23
fwspick_pin = 18

[device_b]  # slave
srst_pin    = 25
fwspick_pin = 24
