# Licensed under the Apache-2.0 license

[package]
name = "openprot-services-storage"
version = "0.1.0"
edition = "2021"
description = "Persistent storage service and abstractions for OpenPRoT"
license = "Apache-2.0"

[dependencies]