[package]
name = "mctp-baremetal"
version = "0.1.0"
edition = "2024"

[dependencies]
mctp-estack = { git = "https://github.com/9elements/mctp-rs.git", branch = "embassy-feature", default-features = false, features = ["log"] }
mctp = { git = "https://github.com/9elements/mctp-rs.git", branch = "embassy-feature", default-features = false }
